export const images = {
  appIconForegroundNeo: require("../assets/images/app-icon-foreground-neo.png"),
  appIconSourceNeo: require("../assets/images/app-icon-source-neo.png"),
  emptyApprovals: require("../assets/images/empty-approvals.png"),
  emptyFollowUps: require("../assets/images/empty-follow-ups.png"),
  emptyInbox: require("../assets/images/empty-inbox.png"),
  emptyProducts: require("../assets/images/empty-products.png"),
  emptyReceipts: require("../assets/images/empty-receipts.png"),
  errorOffline: require("../assets/images/error-offline.png"),
  errorPermissionDenied: require("../assets/images/error-permission-denied.png"),
  errorReceiptUnreadable: require("../assets/images/error-receipt-unreadable.png"),
  errorWhatsappDisconnected: require("../assets/images/error-whatsapp-disconnected.png"),
  iconAiDraft: require("../assets/images/icon-ai-draft.png"),
  iconApprovals: require("../assets/images/icon-approvals.png"),
  iconCustomer: require("../assets/images/icon-customer.png"),
  iconDelivery: require("../assets/images/icon-delivery.png"),
  iconFollowUps: require("../assets/images/icon-follow-ups.png"),
  iconInbox: require("../assets/images/icon-inbox.png"),
  iconOffline: require("../assets/images/icon-offline.png"),
  iconOrder: require("../assets/images/icon-order.png"),
  iconPaid: require("../assets/images/icon-paid.png"),
  iconPermission: require("../assets/images/icon-permission.png"),
  iconProduct: require("../assets/images/icon-product.png"),
  iconReceiptReview: require("../assets/images/icon-receipt-review.png"),
  iconSetNeoCore: require("../assets/images/icon-set-neo-core.png"),
  iconSettings: require("../assets/images/icon-settings.png"),
  iconToday: require("../assets/images/icon-today.png"),
  iconWarning: require("../assets/images/icon-warning.png"),
  illustrationFollowUpRecovery: require("../assets/images/illustration-follow-up-recovery.png"),
  illustrationInboxAiDraft: require("../assets/images/illustration-inbox-ai-draft.png"),
  illustrationReceiptReview: require("../assets/images/illustration-receipt-review.png"),
  illustrationSetupChecklist: require("../assets/images/illustration-setup-checklist.png"),
  illustrationTodayCommandCenter: require("../assets/images/illustration-today-command-center.png"),
  logoMarkNeo: require("../assets/images/logo-mark-neo.png"),
  mascotNeoGuideObject: require("../assets/images/mascot-neo-guide-object.png"),
  onboardingHeroAppPreview: require("../assets/images/onboarding-hero-app-preview.png"),
  onboardingHeroNeoOperatingSystem: require("../assets/images/onboarding-hero-neo-operating-system.png"),
  splashScreenNeo: require("../assets/images/splash-screen-neo.png"),
  styleAnchorNeoCommerceSystem: require("../assets/images/style-anchor-neo-commerce-system.png"),
  successFollowUpSent: require("../assets/images/success-follow-up-sent.png"),
  successOrderCreated: require("../assets/images/success-order-created.png"),
  successPaymentVerified: require("../assets/images/success-payment-verified.png"),
  successReplySent: require("../assets/images/success-reply-sent.png"),
} as const;

export type ImageKey = keyof typeof images;
